version: "3"

services:
  app:
    container_name: lipid_exp_container
    build:
      context: .
      dockerfile: Dockerfile
    image: lipid_exp:latest
    restart: always
    volumes:
      - .:/app
    ports:
      - "8502:8502"
volumes:
  postgres-data:
  test-postgres-data:
